require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'

target 'Bini' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['RCT_NEW_ARCH_ENABLED'] = 'NO'
      end
    end
  end
end